name: assign-author

on:
  issues:
    types: [ opened, reopened ]
  pull_request_target:
    types: [ opened, reopened, ready_for_review ]

permissions:
  issues: write
  pull-requests: write

jobs:
  assign-author:
    runs-on: ubuntu-22.04
    steps:
      - uses: toshimaru/auto-author-assign@v1.6.2
